twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_3_layout.html.twig']
    globals:
        name_site:        '%env(APP_NAME)%'
        base_url:         '%env(BASE_URL)%'
        version:          '%env(APP_VERSION)%'
        name_admin:       '%env(ADMIN_NAME)%'
        name_admin_sigla: '%env(ADMIN_NAME_SIGLA)%'
        locales: '%app_locales%'
